-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgYKEJiztmhQjMh86v
uHS08gOJBnWf+Byb/qkJFDInDfegCgYIKoZIzj0DAQehRANCAARKvDTv445elTXV
JOaFEQ+oBbax+gnDXsGwWM0tRvCqZyqPcDKp0xR/5pvjeoDC9+n2ovepoWEEy//v
TcbNRSY9
-----END PRIVATE KEY-----